name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  APP_CI: true
  DB_NAME: ${{ secrets.DB_NAME }}
  SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
  TOKEN_SYMMETRIC_KEY: ${{ secrets.TOKEN_SYMMETRIC_KEY }}
  ACCESS_TOKEN_DURATION: ${{ secrets.ACCESS_TOKEN_DURATION }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
        id: go
      
      - name: Install golang migration
        run: | 
          go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
          which migrate

      - name: Run migration
        run: migrate -database "sqlite3://${{ secrets.DB_NAME }}" -path "db/migrations" -verbose up

      - name: Run test module
        run: go test -v -cover ./...
