name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
        id: go
      
      - name: Install golang migration
        run: | 
          go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
          which migrate

      - name: Run migration
        run: migrate -database "sqlite3://inventory.db" -path "db/migrations" -verbose up
