name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v4

      - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
      id: go

      - name: Set up SQLite
        uses: actions/setup-sqlite@v1
        with:
          sqlite-version: 3.40.1
          sqlite-year: 2022
          run: sqlite3 inventory.db "VACUUM;"
      
      - name: Install golang migration
        run: | 
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migration
        run: migrate -database "sqlite3://inventory.db" -path "db/migrations" -verbose up
